services:
  phoenixd:
    build:
      context: .
      args:
        ARCH: amd64
    restart: always
    ports:
      - "9740:9740"
    volumes:
      - ./phoenix-data:/phoenix/.phoenix
      - ./satdress-data:/phoenix/.satdress